@host = http://localhost:9200
@index = my-index

### (Optional) Clean start: delete if exists
DELETE {{host}}/{{index}}
Authorization: Basic ZWxhc3RpYzp0ZXN0X0hQU1ZSJnRTb0ElZXhYSGR3dg==

### Create index with mappings
PUT {{host}}/{{index}}
Authorization: Basic ZWxhc3RpYzp0ZXN0X0hQU1ZSJnRTb0ElZXhYSGR3dg==
Content-Type: application/json

{
  "settings": {
    "number_of_shards": 1
  },
  "mappings": {
    "properties": {
      "dateField": { "type": "date" },
      "textField": { "type": "text" }
    }
  }
}

### Bulk insert: 6 monthly docs over half a year (Jan–Jun 2025)
POST {{host}}/_bulk?refresh=wait_for
Authorization: Basic ZWxhc3RpYzp0ZXN0X0hQU1ZSJnRTb0ElZXhYSGR3dg==
Content-Type: application/x-ndjson

< documents-bulk.ndjson

### Sanity check: list all docs
GET {{host}}/{{index}}/_search?size=100&pretty
Authorization: Basic ZWxhc3RpYzp0ZXN0X0hQU1ZSJnRTb0ElZXhYSGR3dg==
Content-Type: application/json

{
  "query": { "match_all": {} },
  "sort": [{ "dateField": "asc" }]
}

### Global agg, which behaves differently in ES8
GET {{host}}/{{index}}/_search?size=0&pretty
Authorization: Basic ZWxhc3RpYzp0ZXN0X0hQU1ZSJnRTb0ElZXhYSGR3dg==
Content-Type: application/json

{
  "query": {
    "bool": {
      "filter": [
        {
          "range": {
            "dateField": {
              "lt": "2025-04-01"
            }
          }
        }
      ]
    }
  },
  "aggs": {
    "all_docs": {
      "global": {},
      "aggs": {
        "by_month": {
          "date_histogram": {
            "field": "dateField",
            "calendar_interval": "month",
            "min_doc_count": 1
          }
        },
        "by_month_terms": {
          "terms": {
            "field": "dateField",
            "min_doc_count": 1
          }
        }
      }
    }
  }
}