services:
  es01:
    extends:
      file: elasticsearch-base.yml
      service: elasticsearch
    environment:
      - node.name=es01
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
    volumes:
      - es-data01:/usr/share/elasticsearch/data

  es02:
    extends:
      file: elasticsearch-base.yml
      service: elasticsearch
    environment:
      - node.name=es02
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
    volumes:
      - es-data02:/usr/share/elasticsearch/data

  es03:
    extends:
      file: elasticsearch-base.yml
      service: elasticsearch
    environment:
      - node.name=es03
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
    volumes:
      - es-data03:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:${ES_IMAGE_TAG}
    restart: unless-stopped
    environment:
      - ELASTICSEARCH_HOSTS=http://es01:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=$ELASTIC_PASSWORD
    ports:
      - "5601:5601"
    depends_on:
      - es01
    networks:
      - elastic-stack
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -f http://localhost:5601 || exit 1",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

networks:
  elastic-stack:

volumes:
  es-data01: {}
  es-data02: {}
  es-data03: {}
