services:
  es01:
    extends:
      file: elasticsearch-base.yml
      service: elasticsearch
    environment:
      - node.name=es01
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
    volumes:
      - es-data01:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  es02:
    extends:
      file: elasticsearch-base.yml
      service: elasticsearch
    environment:
      - node.name=es02
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
    volumes:
      - es-data02:/usr/share/elasticsearch/data

  es03:
    extends:
      file: elasticsearch-base.yml
      service: elasticsearch
    environment:
      - node.name=es03
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
    volumes:
      - es-data03:/usr/share/elasticsearch/data

networks:
  elastic-stack:

volumes:
  es-data01: {}
  es-data02: {}
  es-data03: {}
