services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ES_IMAGE_TAG}
    restart: unless-stopped
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elastic-stack
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '5G'
    environment:
      - xpack.security.enabled=false
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -f http://localhost:9200 || exit 1",
        ]
      interval: 10s
      timeout: 10s
      retries: 120
