services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ES_IMAGE_TAG}
    restart: unless-stopped
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elastic-stack
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '2G'
    environment:
      - cluster.name=foo
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
      - xpack.security.enabled=$ELASTIC_SECURITY
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -f http://localhost:9200 || exit 1",
        ]
      interval: 10s
      timeout: 10s
      retries: 120
