services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ES_IMAGE_TAG}
    restart: unless-stopped
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elastic-stack
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '1G'
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ./elasticsearch/plugins:/usr/share/elasticsearch/plugins:ro